export const strings = {
  general: {
    edit: 'Edytuj',
    delete: 'Usuń',
    save: 'Zapisz',
    cancel: 'Anuluj',
    close: 'Zamknij',
    submit: 'Wyślij',
    yes: 'Tak',
    no: 'Nie',
    other: 'Inne',
    age: 'Wiek',
    weight: 'Waga',
    kg: 'kg',
    confirm: 'Potwierdź',
    are_you_sure: 'Czy na pewno?',
    unauthorized: 'Nieautoryzowany dostęp',
  },
  header: {
    title: 'Psi Behawiorysta AI',
  },
  app_sidebar: {
    home: 'Pulpit',
    your_dogs: 'Twoje psy',
    history: 'Historia',
    settings: 'Ustawienia',
  },
  home: {
    welcome: 'Witaj',
    welcome_description:
      'Cieszymy się, że jesteś z nami. Jesteśmy tu, aby pomóc Ci w szkoleniu Twojego psa.',
    get_started: 'Zacznij',
    get_started_description:
      'Aby rozpocząć współpracę z psim behawiorystą AI należy stworzyć profil swojego psa.',
    sign_in_to_view_this_page: 'Zaloguj się, aby zobaczyć tę stronę',
  },
  dogs: {
    add_dog: 'Dodaj psa',
    edit_dog: 'Edytuj psa',
    delete: 'Usuń profil',
    name: 'Imię',
    name_description: 'To jest imię Twojego psa',
    gender: 'Płeć',
    gender_description: 'Wybierz płeć swojego psa',
    male: 'Samiec',
    female: 'Samica',
    remove_description: 'Are you sure you want to remove this dog profile?',
    more_info: 'Więcej informacji',
    remove_profile: 'Usuń profil',
    there_is_no_dog_to_edit: 'Nie ma psa do edytowania!',
    there_is_no_dog: 'Nie znaleziono psa',
    new_thread: 'Rozpocznij nowy wątek',
    recent_conversation: 'Lista poprzednich konwersacji',
  },
  first_dog_page: {
    paragraph1:
      'Aby rozpocząć współpracę z psim behawiorystą AI należy stworzyć profil swojego psa.',
    paragraph2: 'Obiecujemy, że zajmie to zaledwie kilka minut.',
    paragraph3:
      'Prosimy odpowiedzieć na wszystkie pytania, co na pewno przełoży się na jakość udzielanych porad.',
  },
  new_dog_form: {
    upload_photo: 'Upload a photo of your dog (max 3MB).',
    name_label: 'Name',
    name_description: 'This is your dog name.',
    gender_label: 'Gender',
    gender_description: 'This is your dog gender',
    gender_male: 'Male',
    gender_female: 'Female',
    birthday_label: 'Date of birth',
    birthday_description: 'Your date of birth is used to calculate your age.',
    breed_label: 'Rasa',
    breed_placeholder: 'Select breed',
    breed_description: 'This is your dog breed.',
    breed_other_placeholder: 'Other breed',
    breed_empty_label: 'No breeds found.',
    weight_label: 'Waga',
    weight_description: 'This is your dog weight (kg)',
    health_problems_label: 'Health problems',
    health_problems_description:
      'Does your dog have any health problems? Yes / No',
    health_problems_yes: 'Yes',
    health_problems_no: 'No',
    health_problems_details_label: 'Health problems details',
    health_problems_details_description:
      'This is your dog medical history (chronic diseases, allergies,etc.)',
    activity_level_label: 'Czas aktywnosci',
    activity_level_description: 'Czas aktywności ruchowej psa',
    activity_level_1: 'Do 1h',
    activity_level_2: '1-2h',
    activity_level_3: 'Więcej niż 2 godziny',
    activity_level_4: 'Pies pracujący',
    castrated_label: 'Was he castrated?',
    castrated_description: 'Was he castrated? Yes / No',
    castrated_yes: 'Yes',
    castrated_no: 'No',
    origin_label: 'Skad jest?',
    origin_breeding: 'Hodowla',
    origin_shelter: 'Schronisko',
    origin_other: 'Inne',
    origin_description: 'Skąd masz psa',
    origin_other_label: 'Skad jest?',
    origin_other_placeholder: 'Z hodowli / schroniska / od sąsiada',
    basic_food_label: 'Basic food',
    basic_food_placeholder: 'Meat',
    basic_food_description:
      'Suchą karmę / Mokrą karmę / Jedzenie gotowane / Jedzenie surowe',
    relation_to_food_label: 'Stosunek do jedzenia',
    relation_to_food_1: 'A picky eater',
    relation_to_food_2: 'Normal',
    relation_to_food_3: 'A glutton',
    relation_to_food_description:
      'Czy jedzenie go silnie motywuje? Czy jest wybredny? Czy potrafi zjeść wszystko?',
    favorite_snack_label: 'Favorite snack',
    favorite_snack_placeholder: 'Meat',
    favorite_snack_description: 'This is your dog favorite snack.',
    favorite_toy_label: 'Favorite toy',
    favorite_toy_placeholder: 'Ball',
    favorite_toy_description: 'This is your dog favorite toy.',
    favorite_activity_label: 'Favorite activity',
    favorite_activity_placeholder: 'Running',
    favorite_activity_description: 'This is your dog favorite activity.',
    others_placeholder: 'My dog has ....',
    others_description:
      'Jeśli uważasza, że warto dodać coś jeszcze. Np. trudna przeszłość, znaleziony w złym stanie.',
    submit: 'Submit',
    save: 'Save',
  },
};
