export const strings = {
  general: {
    edit: 'Edytuj',
    delete: 'Usuń',
    save: 'Zapisz',
    cancel: 'Anuluj',
    close: 'Zamknij',
    submit: 'Wyślij',
    yes: 'Tak',
    no: 'Nie',
    other: 'Inne',
    age: 'Wiek',
    weight: 'Waga',
    kg: 'kg',
    confirm: 'Potwierdź',
    are_you_sure: 'Czy na pewno?',
    unauthorized: 'Nieautoryzowany dostęp',
  },
  header: {
    title: 'Psi Behawiorysta AI',
  },
  app_sidebar: {
    home: 'Pulpit',
    your_dogs: 'Twoje psy',
    history: 'Historia',
    settings: 'Ustawienia',
  },
  home: {
    welcome: 'Witaj',
    welcome_description:
      'Cieszymy się, że jesteś z nami. Jesteśmy tu, aby pomóc Ci w szkoleniu Twojego psa.',
    get_started: 'Zacznij',
    get_started_description:
      'Aby rozpocząć współpracę z psim behawiorystą AI należy stworzyć profil swojego psa.',
    sign_in_to_view_this_page: 'Zaloguj się, aby zobaczyć tę stronę',
  },
  dogs: {
    add_dog: 'Dodaj psa',
    edit_dog: 'Edytuj psa',
    delete: 'Usuń profil',
    name: 'Imię',
    name_description: 'To jest imię Twojego psa',
    gender: 'Płeć',
    gender_description: 'Wybierz płeć swojego psa',
    male: 'Samiec',
    female: 'Samica',
    remove_description: 'Are you sure you want to remove this dog profile?',
    more_info: 'Więcej informacji',
    remove_profile: 'Usuń profil',
    there_is_no_dog_to_edit: 'Nie ma psa do edytowania!',
    there_is_no_dog: 'Nie znaleziono psa',
    new_thread: 'Rozpocznij nowy wątek',
    recent_conversation: 'Lista poprzednich konwersacji',
  },
  first_dog_page: {
    paragraph1:
      'Aby rozpocząć współpracę z psim behawiorystą AI należy stworzyć profil swojego psa.',
    paragraph2: 'Obiecujemy, że zajmie to zaledwie kilka minut.',
    paragraph3:
      'Prosimy odpowiedzieć na wszystkie pytania, co na pewno przełoży się na jakość udzielanych porad.',
  },
  new_dog_form: {
    upload_photo: 'Prześlij zdjęcie swojego psa (maks. 3MB).',
    name_label: 'Imię',
    name_description: 'To jest imię Twojego psa.',
    gender_label: 'Płeć',
    gender_male: 'Samiec',
    gender_female: 'Samica',
    birthday_label: 'Data urodzenia',
    breed_label: 'Rasa',
    breed_placeholder: 'Wybierz rasę',
    breed_description: 'To jest rasa Twojego psa.',
    breed_other_placeholder: 'Inna rasa',
    breed_empty_label: 'Nie znaleziono ras.',
    weight_label: 'Waga',
    weight_description: 'To jest waga Twojego psa (kg)',
    health_problems_label: 'Problemy zdrowotne',
    health_problems_description:
      'Czy Twój pies ma jakieś problemy zdrowotne? Tak / Nie',
    health_problems_yes: 'Tak',
    health_problems_no: 'Nie',
    health_problems_details_label: 'Szczegóły problemów zdrowotnych',
    health_problems_details_description:
      'Przedstaw historie medyczną Twojego psa wymień jego choroby przewlekłe, alergie itp.',
    activity_level_label: 'Czas aktywności',
    activity_level_description: 'Czas aktywności ruchowej psa',
    activity_level_1: 'Do 1h',
    activity_level_2: '1-2h',
    activity_level_3: 'Więcej niż 2 godziny',
    activity_level_4: 'Pies pracujący',
    castrated_label: 'Czy był wykastrowany?',
    castrated_description: 'Czy był wykastrowany? Tak / Nie',
    origin_label: 'Skąd jest?',
    origin_breeding: 'Hodowla',
    origin_shelter: 'Schronisko',
    origin_other: 'Inne',
    origin_description: 'Skąd masz psa',
    origin_other_label: 'Skad jest?',
    origin_other_placeholder: 'Z hodowli / schroniska / od sąsiada',
    basic_food_label: 'Podstawowa dieta',
    basic_food_placeholder: 'Mięso drobiowe i gotowane warzywa',
    basic_food_description:
      'Opisz podstawową dietę psa. Np. Sucha karma / Mokrą karmę / Jedzenie gotowane / Jedzenie surowe. Czy lubi warzywa i owoce itp.',
    relation_to_food_label: 'Stosunek do jedzenia',
    relation_to_food_1: 'Wybredny',
    relation_to_food_2: 'Normalny',
    relation_to_food_3: 'Żarłok',
    relation_to_food_description:
      'Czy jedzenie go silnie motywuje? Czy jest wybredny? Czy potrafi zjeść wszystko?',
    favorite_snack_label: 'Ulubiona przekąska',
    favorite_snack_placeholder: 'Meat',
    favorite_toy_label: 'Ulubiona zabawka',
    favorite_activity_label: 'Ulubiona aktywność',
    others_placeholder: 'Mój pies ma ....',
    others_description:
      'Jeśli uważasza, że warto dodać coś jeszcze. Np. trudna przeszłość, znaleziony w złym stanie.',
    submit: 'Wyślij',
    save: 'Zapisz',
  },
};
