export const dogBreeds = [
  { label: 'Kundelek', value: 'kundelek' },
  { label: 'Labrador retriever', value: 'labrador-retriever' },
  { label: 'Owczarek niemiecki', value: 'owczarek-niemiecki' },
  { label: 'Yorkshire terrier', value: 'yorkshire-terrier' },
  { label: 'Golden retriever', value: 'golden-retriever' },
  { label: 'Buldog francuski', value: 'buldog-francuski' },
  { label: 'Beagle', value: 'beagle' },
  { label: 'Pudel', value: 'pudel' },
  { label: 'Rottweiler', value: 'rottweiler' },
  { label: 'Chihuahua', value: 'chihuahua' },
  { label: 'Sznaucer miniaturowy', value: 'sznaucer-miniaturowy' },
  { label: 'Shih tzu', value: 'shih-tzu' },
  { label: 'Boxer', value: 'boxer' },
  { label: 'Doberman', value: 'doberman' },
  {
    label: 'Cavalier king charles spaniel',
    value: 'cavalier-king-charles-spaniel',
  },
  { label: 'Siberian husky', value: 'siberian-husky' },
  { label: 'Border collie', value: 'border-collie' },
  { label: 'Akita inu', value: 'akita-inu' },
  { label: 'Dalmatyńczyk', value: 'dalmatynczyk' },
  { label: 'Samoyed', value: 'samoyed' },
  { label: 'Corgi Pembroke', value: 'corgi-pembroke' },
  { label: 'Maltańczyk', value: 'maltanczyk' },
  { label: 'Nowofundland', value: 'nowofundland' },
  { label: 'Alaskan malamute', value: 'alaskan-malamute' },
  { label: 'Whippet', value: 'whippet' },
  { label: 'Berneński pies pasterski', value: 'bernenski-pies-pasterski' },
  { label: 'Shiba inu', value: 'shiba-inu' },
  { label: 'Pomorski szpic miniaturowy', value: 'pomorski-szpic-miniaturowy' },
  { label: 'Jamnik', value: 'jamnik' },
  {
    label: 'Amstaff (American Staffordshire Terrier)',
    value: 'amstaff-american-staffordshire-terrier',
  },
  { label: 'Buldog angielski', value: 'buldog-angielski' },
  { label: 'Mops', value: 'mops' },
  { label: 'Sznaucer średni', value: 'sznaucer-sredni' },
  { label: 'Sznaucer olbrzym', value: 'sznaucer-olbrzym' },
  { label: 'Seter irlandzki', value: 'seter-irlandzki' },
  { label: 'Cocker spaniel angielski', value: 'cocker-spaniel-angielski' },
  { label: 'Cocker spaniel amerykański', value: 'cocker-spaniel-amerykanski' },
  { label: 'Pekińczyk', value: 'pekinczyk' },
  { label: 'Bichon frise', value: 'bichon-frise' },
  { label: 'Papillon', value: 'papillon' },
  { label: 'Basset hound', value: 'basset-hound' },
  { label: 'Basenji', value: 'basenji' },
  { label: 'Bedlington terrier', value: 'bedlington-terrier' },
  {
    label: 'Belgijski owczarek malinois',
    value: 'belgijski-owczarek-malinois',
  },
  {
    label: 'Belgijski owczarek tervueren',
    value: 'belgijski-owczarek-tervueren',
  },
  { label: 'Bergamasco', value: 'bergamasco' },
  { label: 'Bernardyn', value: 'bernardyn' },
  { label: 'Bichon havanese', value: 'bichon-havanese' },
  { label: 'Bloodhound', value: 'bloodhound' },
  { label: 'Bokser', value: 'bokser' },
  { label: 'Boston terrier', value: 'boston-terrier' },
  { label: 'Briard', value: 'briard' },
  { label: 'Bullmastiff', value: 'bullmastiff' },
  { label: 'Cairn terrier', value: 'cairn-terrier' },
  { label: 'Cane corso', value: 'cane-corso' },
  { label: 'Chart afgański', value: 'chart-afganski' },
  { label: 'Chart rosyjski borzoj', value: 'chart-rosyjski-borzoj' },
  { label: 'Chow chow', value: 'chow-chow' },
  { label: 'Collie długowłosy', value: 'collie-dlugowlosy' },
  { label: 'Collie krótkowłosy', value: 'collie-krotkowlosy' },
  { label: 'Dog niemiecki', value: 'dog-niemiecki' },
  { label: 'Dogue de Bordeaux', value: 'dogue-de-bordeaux' },
  { label: 'Flat coated retriever', value: 'flat-coated-retriever' },
  { label: 'Fox terrier', value: 'fox-terrier' },
  { label: 'Glen of Imaal terrier', value: 'glen-of-imaal-terrier' },
  { label: 'Gordon seter', value: 'gordon-seter' },
  { label: 'Greyhound', value: 'greyhound' },
  { label: 'Griffon brukselski', value: 'griffon-brukselski' },
  { label: 'Hovawart', value: 'hovawart' },
  { label: 'Jack Russell terrier', value: 'jack-russell-terrier' },
  { label: 'Keeshond', value: 'keeshond' },
  { label: 'Komondor', value: 'komondor' },
  { label: 'Kooikerhondje', value: 'kooikerhondje' },
  { label: 'Labradoodle', value: 'labradoodle' },
  { label: 'Lagotto romagnolo', value: 'lagotto-romagnolo' },
  { label: 'Leonberger', value: 'leonberger' },
  { label: 'Lhasa apso', value: 'lhasa-apso' },
  { label: 'Mastif angielski', value: 'mastif-angielski' },
  { label: 'Mastif tybetański', value: 'mastif-tybetanski' },
  { label: 'Norfolk terrier', value: 'norfolk-terrier' },
  { label: 'Norwich terrier', value: 'norwich-terrier' },
  { label: 'Owczarek australijski', value: 'owczarek-australijski' },
  { label: 'Owczarek belgijski', value: 'owczarek-belgijski' },
  { label: 'Owczarek szkocki collie', value: 'owczarek-szkocki-collie' },
  { label: 'Puli', value: 'puli' },
  { label: 'Pumi', value: 'pumi' },
  { label: 'Rhodesian ridgeback', value: 'rhodesian-ridgeback' },
  { label: 'Saluki', value: 'saluki' },
  { label: 'Shar pei', value: 'shar-pei' },
  { label: 'Skye terrier', value: 'skye-terrier' },
  { label: 'Spinone italiano', value: 'spinone-italiano' },
  { label: 'Staffordshire bullterrier', value: 'staffordshire-bullterrier' },
  { label: 'Tosa inu', value: 'tosa-inu' },
  { label: 'Weimaraner', value: 'weimaraner' },
  { label: 'Welsh corgi cardigan', value: 'welsh-corgi-cardigan' },
  { label: 'Welsh terrier', value: 'welsh-terrier' },
  {
    label: 'West highland white terrier',
    value: 'west-highland-white-terrier',
  },
  { label: 'Wilczarz irlandzki', value: 'wilczarz-irlandzki' },
  {
    label: 'Wyżeł niemiecki krótkowłosy',
    value: 'wyzel-niemiecki-krotkowlosy',
  },
  { label: 'Wyżeł węgierski', value: 'wyzel-wegierski' },
  { label: 'Złoty retriever', value: 'zloty-retriever' },
  { label: 'Inna', value: 'OTHER' },
] as const;
